config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # callback routing
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show]

  unauthenticated :users do
    # landing page
    root to: 'homes#index', as: :root #-> if user is not logged in
  end

  resources :books do
    resources :articles, except: :index do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :recommends
  resources :article_favs, only: [:create, :destroy]
  resources :recommend_favs, only: [:create, :destroy]
  resources :groups, only: [:create, :destroy]
  resources :regist_books, only: [:create, :destroy]
  resources :tags, only: [:new, :create, :destroy]

  # set letter opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  module NameGen
    (NAME = 'No Name').freeze
  end

  # book association
  has_many :regist_books, dependent: :destroy
  has_many :books, through: :regist_books

  # recommend association
  has_many :recommends, dependent: :destroy
  has_many :recommend_fav, dependent: :destroy
  has_many :favs, through: :recommend_fav, source: :recommend

  # article association
  has_many :articles, dependent: :destroy
  has_many :article_fav, dependent: :destroy
  has_many :article_favs, through: :article_fav, source: :article

  # comment association
  has_many :comments

  # devise setting
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable

  # validate
  validates :name, length: { maximum: 30 }
  validates :email, presence: true, length: { in: 1..254 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    user ||= User.create(
      name: auth.info.name,
      uid: auth.uid,
      provider: auth.provider,
      email: "#{auth.uid}-#{auth.provider}@example.com",
      username: auth.info.nickname,
      password: Devise.friendly_token[0, 20]
    )
    user
  end

  def safe_name
    name.blank? ? NameGen::NAME : name
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < ApplicationController
  skip_before_action :authenticate_user!

  def twitter
    callback_from :twitter
  end

private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callback.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authenticated
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
protected

  def after_update_path_for(_resource)
    user_path(id: current_user.id) # after updated page
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @favs = current_user.favs
    @article_favs = current_user.article_favs
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
# frozen_string_literal: true

module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/show.html.erb
<div class="container profile-body">

  <div class="d-flex flex-row">

    <!-- user data -->
    <div class="col-md-5">
      <div class="media">
        <a class="float-left" href="#">
          <img class="media-object dp rounded-circle" src="<%= asset_url("girl.png") %>" style="width: 100px;height:100px;">
        </a>
        <div class="media-body ml-3">
          <h4 class="media-heading">
            <strong><%= @user.safe_name %></strong>
          </h4>
          <div class="small">
            <% unless @user.provider.blank? %>
              joined via <%= @user.provider %>
            <% else %>
              joined via email
              <div>
                <%= t('views.user.email') %>: <%= @user.email %>
              </div>
            <% end %>
          </div>
          <div class="small">
            <%= t('views.user.started_at') %>: <%= time_present(@user.created_at) %>
          </div>
          <hr style="m-8 mb-8">
          <div>
            <% unless current_user.provider? %>
              <%= link_to t('views.user.profile'), edit_user_registration_path %>
            <% else %>
              <h5><%= t('views.title.cancel') %></h5>
              <%= button_to t('views.user.cancel'), registration_path(@user), { data: { confirm: t('views.message.cancel') }, method: :delete, class: 'btn btn-danger mb-3' } %>
            <% end %>
          </div>
          <div>
            <%= link_to t("views.message.back_home"), books_path, { class: 'btn btn-primary' } %>
          </div>
        </div>
      </div>
    </div>

    <!-- favorite items -->
    <div class="col-md-7">

      <!-- title -->
      <h6><%= t('views.title.favorite') %></h6>

      <!-- item tab -->
      <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
        <%= link_to t('views.title.article'), '#nav-article', { class: 'nav-item nav-link active', id: 'nav-article-tab', role: 'tab', data: { toggle: "tab" }, aria: { controles: 'nav-article', selected: 'true' } } %>
        <%= link_to t('views.title.book_list'), '#nav-book-list', { class: 'nav-item nav-link', id: 'nav-book-group-tab', role: 'tab', data: { toggle: "tab" }, aria: { controles: 'nav-book-group', selected: 'false' } } %>
      </div>

      <!-- item content -->
      <div class="tab-content" id="tabContent">

        <!-- article content -->
        <div  class="tab-pane fade show active" id="nav-article" role="tabpannel" aria-labelledby="nav-article-tab">
          <table class="table" cellspacing="0">
            <thead>
              <tr>
                <th>Writer</th>
                <th>Title</th>
                <th>Up</th>
              </tr>
            </thead>
            <tbody>
              <% @article_favs.each do |article| %>
                <tr class="small">
                  <td>
                    <%= article.user.safe_name %>
                  </td>
                  <td>
                    <%= link_to "#{article.title}", book_article_path(book_id: article.book.id, id: article.id) %>
                  </td>
                  <td>
                    <%= time_present(article.created_at) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <!-- book list content -->
        <div class="tab-pane fade" id="nav-book-list" role="tabpannel" aria-labelledby="nav-book-list-tab">
          <table class="table" cellspacing="0">
            <thead>
              <tr>
                <th>Author</th>
                <th>Title</th>
                <th>Summary</th>
              </tr>
            </thead>
            <tbody>
              <% @favs.each do |recommend| %>
                <tr class="small">
                  <td>
                    <%= link_to "#{recommend.user.safe_name}", recommend_path(recommend) %>
                  </td>
                  <td>
                    <%= truncate(recommend.summary, length:10) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>