config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # callback routing
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show]

  unauthenticated :users do
    # landing page
    root to: 'homes#index', as: :root #-> if user is not logged in
  end

  resources :books do
    resources :articles, except: :index do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :recommends
  resources :article_favs, only: [:create, :destroy]
  resources :recommend_favs, only: [:create, :destroy]
  resources :groups, only: [:create, :destroy]
  resources :regist_books, only: [:create, :destroy]
  resources :tags, only: [:new, :create, :destroy]

  # set letter opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/recommend.rb
# frozen_string_literal: true

class Recommend < ApplicationRecord
  belongs_to :user

  has_many :groups, dependent: :destroy
  has_many :books, through: :groups, source: :book

  # favorites
  has_many :recommend_fav, dependent: :destroy
  has_many :fav_user, through: :recommend_fav, source: :user

  # nested_params
  accepts_nested_attributes_for :books

  # validate
  validates :name, presence: true, length: { in: 1..254 }
  validates :summary, presence: true, length: { maximum: 300 }

  def fav(user)
    recommend_fav.create(user_id: user.id)
  end

  def unfav(user)
    r = recommend_fav.find_by(user_id: user.id)
    r.destroy
  end

  def faved?(user)
    fav_user.where(id: user.id).exists?
  end
end

app/controllers/recommends_controller.rb
# frozen_string_literal: true

class RecommendsController < ApplicationController
  before_action :set_recommend, only: [:edit, :show, :update, :destroy]

  def index
    # user recommend
    @recommend = current_user.recommends

    # other user recommend
    @other_recommends = []
    other_users = User.where.not(id: current_user).reject { |u| u.recommends.empty? }
    other_users.each do |u|
      u.recommends.each { |rec| @other_recommends << rec }
    end
  end

  def show
    @groups = @recommend.groups
    @user = current_user
  end

  def new
    @recommend = Recommend.new

    # require 3 books
    3.times { @recommend.books.build }
  end

  def create
    @recommend = current_user.recommends.new(recommend_params)

    if @recommend.save
      redirect_to recommends_path, notice: t('views.message.book_group')
    else
      flash[:alert] = t('views.message.failed_book_group')
      render :new
    end
  end

  def edit
    @recommend.groups.build
  end

  def update
    if @recommend.update(recommend_params)
      redirect_to recommends_path, notice: t('views.message.update_book_group')
    else
      flash[:alert] = t('views.message.failed_update_book_group')
      render :edit
    end
  end

  def destroy
    @recommend.destroy
    redirect_to recommends_path, alert: t('views.message.delete_book_group')
  end

private

  def recommend_params
    params.require(:recommend).permit(
      :name,
      :summary,
      books_attributes: [
        :id,
        :_destroy,
        :title,
        :publish_on,
        :sheets,
        :price,
        :image
      ]
    )
  end

  def set_recommend
    @recommend = Recommend.find(params[:id])
  end
end

app/helpers/recommend_helper.rb
# frozen_string_literal: true

module RecommendHelper
  def recommend_choose_new_or_edit
    if action_name == 'edit'
      recommend_path
    else
      recommends_path
    end
  end

  def fav_count(recommend)
    RecommendFav.where(recommend_id: recommend.id).count
  end
end

app/views/recommends/_form.html.erb
<%= form_with(model: @recommend, local: true, url: recommend_choose_new_or_edit) do |f| %>

  <table class="recommend-form-table">
    <tbody>

      <tr class='form_group'>
        <th>
          <%= f.label :name, t('views.recommend.name') %>
        </th>
        <td id="group_name">
          <%= f.text_field :name, { class: 'form-control', placeholder: t('views.recommend.name_placeholder') } %>
        </td>
      </tr>

      <tr class='form_group'>
        <th>
          <%= f.label :summary, t('views.recommend.summary') %>
        </th>
        <td>
          <%= f.text_area :summary, { class: 'form-control', rows: 5, placeholder: t('views.recommend.summary_placeholder')} %>
        </th>
      </tr>
    </tbody>
  </table>

  <div class="text-dark my-3">
    <h3><%= t('views.title.books_form') %></h3>
  </div>


  <table class="form-inline book-form-inline">

      <%= f.fields_for :books do |b| %>
        <div class="align-items-center">
          <th>
            Book
            <%= b.options[:child_index] + 1 %>
          </th>

          <td>
            <%= b.text_field :title, { class: 'form-control', placeholder: t('views.recommend.book_form') } %>
          </td>

          <td>
            <%= b.date_select :publish_on, {}, { class: 'form-control' } %>
          </td>

          <td>
            <%= b.number_field :sheets, { min: 0, max: 10000000, step: 1, class: "form-control", placeholder: 'pages' } %>
          </td>

          <td>
            <%= b.number_field :price, { min: 1, max: 10000000, step: 1, class: 'form-control', placeholder: 'yen' } %>
          </td>

          <td>
            <label>
              <span class="btn btn-primary">
                File
                <%= b.file_field :image, { class: 'form-control-file', style: "display:none" } %>
              </span>
            </label>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= f.submit(class: 'btn btn-primary my-3')%>
<% end %>

<% if @recommend.errors.any? %>
  <% @recommend.errors.full_messages.each do |msg| %>
    <script>
      toastr.options = {
        "positionClass": "toast-bottom-left",
        "preventDuplicates": false,
        "timeOut": "10000",
      }
      toastr['error']('<%= msg %>')
    </script>
  <% end %>
<% end %>

app/views/recommends/edit.html.erb
<div class="container-fluid recommend-background">
  <div class="container bg-white">
    <!-- back link -->
    <%= link_to recommends_path do %>
      <%= icon('fas', 'angle-left') %> back to book group list
    <% end %>

    <h3 class="text-dark mt-3">
      <%= t('views.title.recommend_edit') %>
    </h3>
    <%= render 'form' %>
  </div>
</div>

app/views/recommends/index.html.erb
<!-- page title -->
<h4 class="recommend-heading">
  <div class="container">
    <%= t('views.title.book_list') %>
    <%= link_to t('views.button.new'), new_recommend_path, { class: 'btn btn-sm btn-primary btn-new' } %>
  </div>
</h4>
<div class="container-fluid recommend-container">
  <div class="container py-2 recommend-back-link">
    <!-- back link -->
    <%= link_to books_path do %>
      <%= icon('fas', 'angle-left') %> back to book list
    <% end %>
  </div>

  <!-- main container -->
  <div class="container recommend-table d-flex flex-row">

    <!-- select menue -->
    <div class="col-4">
      <div class="list-group" id="list-tab" role="tablist">
        <%= link_to t('views.title.my_groups'), '#my-group', { class: 'list-group-item list-group-item-action active', data: { toggle: 'list' }, role: "tab" } %>
        <%= link_to t('views.title.other_groups'), '#other-group', { class: 'list-group-item list-group-item-action', data: { toggle: 'list' }, role: "tab" } %>
      </div>
    </div>

    <!-- contents -->
    <div class="col-8">
      <div class="tab-content">

        <!-- my-group content -->
        <div class="tab-pane active" id="my-group" role="tabpannel">
          <% @recommend.each do |r| %>
            <div class="d-flex flex-row">

              <div class="col-md-6">
                <h3>
                  <%= link_to r.name, recommend_path(r.id) %>
                  <small>
                    <%= "#{fav_count(r)} faved"%>
                    <%= icon('fas', 'heart') %>
                  </small>
                </h3>
                <p class="small">
                  <%= r.summary.truncate(120) %><br />
                  <%= t('views.recommend.created_at') %>: <%= time_present(r.created_at) %>
                </p>
              </div>

              <div class="col-md-6">
                <% if r.books.exists? %>
                  <%= image_tag(r.books.first.image.to_s, :size => '90x90', class: 'thumbnail') %>
                  <%= image_tag(r.books.second.image.to_s, :size => '90x90', class: 'thumbnail') %>
                  <%= image_tag(r.books.third.image.to_s, :size => '90x90', class: 'thumbnail') %>
                <% end %>
              </div>

            </div>
            <hr>
          <% end %>
        </div>

        <!-- other-group content -->
        <div class="tab-pane" id="other-group" role="tabpannel">
          <% @other_recommends.each do |r| %>
            <div class="d-flex flex-row">
              <div class="col-md-6">
                <h3>
                  <%= link_to r.name, recommend_path(r.id) %>
                  <small>
                    <%= "#{fav_count(r)} faved"%>
                    <%= icon('fas', 'heart') %>
                  </small>
                </h3>
                <p class="small mb-0">
                  <%= r.summary.truncate(25) %><br />
                  <%= t('views.recommend.written_by') %>: <%= r.user.safe_name %><br />
                  <%= t('views.recommend.created_at') %>: <%= time_present(r.created_at) %><br />
                </p>
              </div>

              <!-- registed books -->
              <div class="col-md-6">
                <% if r.books.exists? %>
                  <%= image_tag(r.books.first.image.to_s, :size => '90x90', class: 'thumbnail') %>
                  <%= image_tag(r.books.second.image.to_s, :size => '90x90', class: 'thumbnail') %>
                  <%= image_tag(r.books.third.image.to_s, :size => '90x90', class: 'thumbnail') %>
                <% end %>
              </div>

            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/recommends/new.html.erb
<div class="container-fluid recommend-background">
  <div class="container bg-white">
    <!-- back link -->
    <%= link_to recommends_path do %>
      <%= icon('fas', 'angle-left') %> back to book group list
    <% end %>

    <h3 class="text-dark mt-3">
      <%= t('views.title.new_recommend') %>
    </h3>
    <%= render 'form' %>
  </div>
</div>

app/views/recommends/show.html.erb
<div class="container recommend_detail_container">

  <div class="media group-media my-0">
    <%= image_tag('group.png', size: '60x60') %>
    <div class="media-body">
      <!-- page title -->
      <h4 class="my-2">
        <strong class="mr-5"><%= @recommend.name %></strong>
        <small>
          <%= link_to t('views.button.edit'), edit_recommend_path(@recommend.id), { class: 'btn btn-sm btn-info' } %>
          <%= link_to t('views.button.delete'), recommend_path(@recommend.id), { method: :delete, class: 'btn btn-sm btn-danger' } %>
          <%= render 'recommend_favs/fav', recommend: @recommend %>
        </small>
      </h4>

      <!-- book group info -->
      <div>
        <%= icon('fas', 'user-edit') %>
        <strong class="mr-1">
          <%= t('views.user.author') %>
        </strong>
        <%= @user.safe_name %>
      </div>
      <p class="mb-0">
        <%= icon('fas', 'scroll') %>
        <strong class="mr-1">
          <%= t('views.recommend.summary') %>
        </strong>
        <%= @recommend.summary %>
      </p>
    </div>
  </div>

  <!-- contents flex layout -->
  <div class="card-deck mb-3">

    <% @groups.each do |g| %>
    <!-- each book info -->
      <div class="card">
        <%= link_to image_tag( g.book.image.to_s, :size => '90x90', class: 'thumbnail p-1'), book_path(g.book.id) %>

        <div class="card-body small">
          <!-- book detail info-->
          <strong class="card-title strong">
            <%= g.book.title %>
          </strong>

          <div class="card-text">
            <%= t('views.book.publish_on') %>: <%= g.book.publish_on.nil? ? t('views.message.no_data') : "#{time_present(g.book.publish_on)}" %>
          </div>
          
          <div class="card-text">
            <%= t('views.book.sheets') %>: <%= g.book.sheets.nil? ? t('views.message.no_data') : "#{g.book.sheets} page" %>
          </div>

          <div class="card-text">
            <%= t('views.book.price') %>: <%= g.book.price.nil? ? t('views.message.no_data') : "#{g.book.price} yen" %>
          </div>

          <div class="card-text">
            <%= t('views.book.tags') %>:
            <% if g.book.tag_list.present? %>
              <%= render 'books/tag_list', tag_list: g.book.tag_list %>
            <% else %>
              <%= t('views.message.no_data') %>
            <% end %>
          </div>

        </div>

        <div class="card-footer">
          <!-- regist book button -->
          <% if is_regist?(g.book) %>
            <%= link_to  t('views.button.unregist_book'), regist_book_path(g.book.id), { method: :delete, class: "btn btn-sm btn-danger" } %>
          <% else %>
            <%= link_to t('views.button.regist_book'), regist_books_path(book_id: g.book.id), { method: :post, class: "btn btn-sm btn-info" } %>
          <% end %>
        </div>

      </div>
    <% end %>
  </div>

</div>