config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # callback routing
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show]

  unauthenticated :users do
    # landing page
    root to: 'homes#index', as: :root #-> if user is not logged in
  end

  resources :books do
    resources :articles, except: :index do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :recommends
  resources :article_favs, only: [:create, :destroy]
  resources :recommend_favs, only: [:create, :destroy]
  resources :groups, only: [:create, :destroy]
  resources :regist_books, only: [:create, :destroy]
  resources :tags, only: [:new, :create, :destroy]

  # set letter opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :regist_books, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :recommends, through: :groups, source: :recommend
  has_many :articles, dependent: :destroy

  # to user carrierwave
  mount_uploader :image, ImageUploader

  # alias act_as_tagglable_on :tags
  acts_as_taggable

  # validate
  validates :title, presence: true, length: { in: 1..10_000 }
  validates :publish_on, presence: true, date: true
  validates :sheets, numericality: { allow_nil: true, only_integer: true, greater_than_or_equal_to: 0 }
  validates :price, numericality: { allow_nil: true, only_integer: true, greater_than_or_equal_to: 0 }

  # define search validation by ransack
  def self.ransackable_attributes(*)
    %w[title]
  end

  def self.ransackable_associations(*)
    %w[articles]
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :show, :update, :destroy]

  def index
    @q = current_user.books.ransack(params[:q])

    if params[:tag_name]
      books = current_user.books.tagged_with(params[:tag_name].to_s)
      @books = books.page(params[:page]).per(10)
    else
      @books = @q.result(distinct: true).page(params[:page]).per(10)
    end
  end

  def show
    # initialize other user's articles
    @other_articles = []

    other_users = User.where.not(id: current_user).reject { |u| u.articles.where(book_id: @book.id).empty? }
    other_users.each do |u|
      u.articles.where(book_id: @book.id).each { |article| @other_articles << article }
    end

    # return my articles
    @articles = current_user.articles.where(book_id: @book, user_id: current_user)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      # regist user's book list
      current_user.regist_books.build(book_id: @book.id).save
      redirect_to books_path, notice: t('views.message.regist_book')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to books_path, notice: t('views.message.update_book')
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: t('views.message.delete_book')
  end

private

  def book_params
    params.require(:book).permit(:title, :publish_on, :sheets, :price, :image, :tag_list)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
  require 'time'

  def book_choose_new_or_edit
    if action_name == 'edit'
      book_path
    else
      books_path
    end
  end

  def is_regist?(book)
    current_user.regist_books.find_by(book_id: book.id)
  end

  def book_articles(book)
    current_user.articles.where(book_id: book).order(updated_at: 'DESC').limit(5)
  end
end

app/views/books/_form.html.erb
<%= form_with(model:@book, local:true, url: book_choose_new_or_edit) do |f| %>

  <table class="form-table">
    <tbody>

      <tr class="form-group">
        <th>
          <%= f.label :title, t('views.book.title') %>
        </th>
        <td style="min-width:500px;">
          <%= f.text_field :title, {class: 'form-control', placeholder: '例：ヒト夜の永い夢はたった6枚の冴えたトンカツ'} %>
        </td>
      </tr>

      <tr class="form-group">
        <th>
          <%= f.label :publish_on, t('views.book.publish_on') %>
        </th>
        <td class="d-flex flex-row">
          <%= f.date_select :publish_on, {}, { class: 'form-control' } %>
        </td>
      </tr>

      <tr class="form-group clearfix">
        <th>
          <%= f.label :sheets, t('views.book.sheets') %>
        </th>
        <td class="float-left">
          <%= f.number_field :sheets, min: 0, max: 10000000, step: 1 %> pages
        </td>
      </tr>

      <tr class="form-group clearfix">
        <th>
          <%= f.label :price, t('views.book.price') %>
        </th>
        <td class="float-left">
          <%= f.number_field :price, min: 1, max: 10000000, step: 1 %> yen
        </td>
      </tr>

      <tr class="form-group clearfix">
        <th>
          <%= f.label :image, t('views.book.image') %>
        </th>
        <td class="float-left">
          <%= f.file_field :image %>
        </td>
      </tr>

      <tr class="form-group">
        <th>
          <%= f.label :tag_list, t('views.book.tags') %>
        </th>
        <td>
          <%= f.text_field :tag_list, { value: @book.tag_list.join(','), id: "tag-input", class: "form-control", placeholder: t('views.book.tags_explain') } %>
        </td>
      </tr>

    </tbody>
  </table>

  <p class="book-submit">
    <%= f.submit( class: 'btn btn-info' )%>
  </p>

<% end %>
<script type="text/javascript">
$(function() {
    var tags_explain = "<%= t('views.book.tags_explain') %>";
    $('#tag-input').tagit({placeholderText: tags_explain});
});
</script>

<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |msg| %>
    <script>
      toastr.options = {
        "closeButton": true,
        "positionClass": "toast-bottom-left",
        "preventDuplicates": false,
        "timeOut": "2000",
      }
      toastr['error']('<%= msg %>')
    </script>
  <% end %>
<% end %>

app/views/books/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="badge badge-primary my-1 mr-1 p-2">
    <%= link_to tag, books_path(tag_name: tag), { class: "text-white" } %>
  </span>
<% end %>

app/views/books/edit.html.erb
<div class="container bg-white pt-3">
  <!-- back link -->
  <%= link_to books_path do %>
    <%= icon('fas', 'angle-left') %> back to book list
  <% end %>

  <h3 class="mt-2">
    <%= t('views.title.edit_book') %>
  </h3>

  <small>
    本の情報の更新
  </small>

  <%= render 'form' %>
</div>

app/views/books/index.html.erb
<div class="container-fulid book_index_container">
  <div class="page title">

    <!-- search book title or article title -->
    <%= search_form_for(@q, class: 'mb-2') do |f| %>
      <div class="form-group d-flex flex-row mb-0">
        <div class="col-sm-4"></div>
        <%= f.label :title_or_articles_title_cont, 'Title', { class: 'sr-only' } %>
        <%= f.search_field :title_or_articles_title_cont, { class: 'col-sm-4 form-control mt-3', placeholder: 'Search Your Book Title or Article Title'} %>
        <div class="col-sm-1">
          <%= f.submit(class: 'btn btn-danger mt-3') %>
        </div>
      </div>
    <% end %>

    <!-- book list -->
    <h4 class="text-white">
      <%= t('views.title.books') %>
      <%= link_to new_book_path, { class: 'ml-3 btn btn-primary' } do %>
        <%= icon('fas', 'book', class: 'pr-2') %>
        <%= t('views.message.add_new_book') %>
      <% end %>
    </h4>
  </div>

  <% if @books.exists? %>

    <div class="card-columns">

      <% @books.each do |book| %>

        <div class="card book-card bg-white">

          <div class="d-flex flex-row no-gutters ">

            <!-- book title -->
            <div class="col-md-4">
              <%= link_to image_tag(book.image.url, :size => '100x80', class: 'book-image'), book_path(book.id), { class: 'card-img' } %>
              <span class="badge badge-pill badge-success small">Article</span> <%= book.articles.where(user_id: current_user).count %>
            </div>

            <div class="col-md-8">
              <div class="card-body">
                <% if book.articles.present? %>
                  <span class="badge badge-pill badge-warning">up</span>
                  <span class="small"><%= time_present(book.articles.last.updated_at) %></span>
                <% end %>
                <h4 class="card-title"><%= link_to book.title, book_path(book.id), { class: 'text-dark' } %></h4>
                <hr>
                <div class="d-flex flex-column">
                  <% unless book.articles.present? %>
                    <div class="col-md-12 mb-3 small">
                      <%= t('views.message.no_article') %>
                    </div>
                  <% end %>
                  <% book_articles(book.id).each do |ar| %>
                    <%= link_to " #{truncate(ar.title, length: 18)}", book_article_path(id: ar.id, book_id: book.id), { class:"fa fa-book p-2 card-text small" } %>
                  <% end %>
                  <div class="justify-content-end">
                    <%= link_to t('views.message.new_article'), new_book_article_path(book.id), { class: "btn btn-sm btn-primary col-mb-1 fas fa-pen" } %>
                  </div>
                </div>

              </div>
            </div>

          </div>

        </div>

      <% end %>
    </div>

    <!-- paginate -->
    <%= paginate @books %>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="container bg-white pt-3">
  <!-- back link -->
  <%= link_to books_path do %>
    <%= icon('fas', 'angle-left') %> back to book list
  <% end %>

  <h3 class="mt-2">
    <%= t('views.title.regist_book') %>
  </h3>

  <p class="small">
    <%= t('views.message.book_input') %>
  </p>

  <%= render 'form' %>

</div>

app/views/books/show.html.erb
<div class="container-fulid book-detial-container clearfix">
  <h4>
    <%= t('views.title.book_detail') %>
  </h4>
  <div class="d-flex">
    <div class="col-md-5 media p-0 m-0">
      <div class="flex-column">
        <%= image_tag( @book.image.to_s, :size => '180x180', class: 'thumbnail')%>
        <div class="ml-3 pt-3">
          <% if is_regist?(@book) %>
            <%= link_to t('views.message.unregist'), regist_book_path(@book.id), { method: :delete, class: "btn btn-sm btn-danger" } %>
          <% else %>
            <%= link_to t('views.message.regist'), regist_books_path(book_id: @book.id), { method: :post, class: "btn btn-sm btn-info" } %>
          <% end %>
        </div>
      </div>
      <div class="media-body book-detail-body">
        <div class="flex-row">
          <h5>
            <strong><%= @book.title %></strong>
            <%= link_to icon('fas', 'pen'), edit_book_path(@book.id), { class: "book-tooltip btn btn-success btn-sm", title:'編集' } %>
            <%= link_to icon('fas', 'trash-alt'), book_path(@book.id), { method: :delete,  class: "book-tooltip btn btn-danger btn-sm", title:'削除' } %>
          </h5>
        </div>
        <div>
          <span class="col-sm-1">
            <%= t('views.book.publish_on') %>:
          </span>
          <span><%= time_present(@book.publish_on) %></span>
        </div>
        <div>
          <span class="col-sm-1">
            <%= t('views.book.sheets') %>:
          </span>
          <span>
            <%= @book.sheets %> page
          </span>
        </div>
        <div>
          <span class="col-sm-1">
            <%= t('views.book.price') %>:
          </span>
          <span>
            <%= @book.price %> yen
          </span>
        </div>
        <div>
          <% if @book.tag_list.present? %>
            <span class="col-sm-1">
              <%= t('views.book.tags') %>:
            </span>
            <span>
              <%= render 'books/tag_list', tag_list: @book.tag_list %>
            </span>
          <% else %>
            <span class="col-sm-1">
              <%= t('views.book.tags') %>:
            </span>
            <span>
              <%= t('views.message.no_tags') %>
            </span>
          <% end %>
        </div>
      </div>
    </div>

    <!-- related articel tab-->
    <div class="col-md-7">
      <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
        <%= link_to t('views.article.my_article'), '#nav-my-article', { class: 'nav-item nav-link active', id: 'nav-my-article-tab', role: 'tab', data: { toggle: "tab" }, aria: { controles: 'nav-my-article', selected: 'true' } } %>
        <%= link_to t('views.article.other_article'), '#nav-other-article', { class: 'nav-item nav-link', id: 'nav-other-article-tab', role: 'tab', data: { toggle: "tab" }, aria: { controles: 'nav-other-article', selected: 'false' } } %>
      </div>
      <div class="tab-content" id="tabContent">
        <div  class="tab-pane fade show active" id="nav-my-article" role="tabpannel" aria-labelledby="nav-my-article-tab">
          <table class="table" cellspacing="0">
            <thead>
              <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Up</th>
              </tr>
            </thead>
            <tbody>
              <% @articles.each do |article| %>
                <tr class="small">
                  <td>
                    <%= link_to "#{article.title}", book_article_path(book_id: @book, id: article.id) %>
                  </td>
                  <td>
                    <%= truncate(article.body, length: 20)%>
                  </td>
                  <td>
                    <%= time_present(article.created_at) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="tab-pane fade" id="nav-other-article" role="tabpannel" aria-labelledby="nav-other-article-tab">
          <table class="table" cellspacing="0">
            <thead>
              <tr>
                <th>writer</th>
                <th>Title</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              <% @other_articles.each do |article| %>
                <tr class="small">
                  <td>
                    <%= article.user.safe_name %>
                  </td>
                  <td>
                    <%= truncate(article.title, length:10) %>
                  </td>
                  <td>
                    <%= link_to "#{truncate(article.body, length: 20)}", book_article_path(book_id: @book, id: article) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>