config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # callback routing
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show]

  unauthenticated :users do
    # landing page
    root to: 'homes#index', as: :root #-> if user is not logged in
  end

  resources :books do
    resources :articles, except: :index do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :recommends
  resources :article_favs, only: [:create, :destroy]
  resources :recommend_favs, only: [:create, :destroy]
  resources :groups, only: [:create, :destroy]
  resources :regist_books, only: [:create, :destroy]
  resources :tags, only: [:new, :create, :destroy]

  # set letter opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/views/homes/index.html.erb
<!-- site index -->
<section class="home">
  <p class="title-text-sub">
    積読してますか？
  </p>
  <h1 class="title-text">
    Tundocker
  </h1>
  <p class="title-content">
    日々積まれる本たちに悩めるものたちの支援サイト
  </p>
  <% if user_signed_in? %>
    <%= link_to "study now", books_path, { class: "btn btn-primary start-button", type: :button } %>
  <% else %>
    <%= link_to "Regist Now", new_registration_path(:user), { class: 'btn btn-primary start-button', type: :button } %><br />
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize('twitter')}", omniauth_authorize_path('user', 'twitter'), { method: :post, class: 'fab fa-twitter-square text-white' } %>
  <% end %>
</section>

<section class="about" id="about">
  <h2 class="heading">
    ABOUT
  </h2>
  <p class="about-text">
    いつか読もうとしているその積読、みんなで解消！<br />
    技術身につける手段は様々ですが、本は数ある手段の中でもいまだに有用であると思います。<br/>
    ですが、本を読むだけで内容を定着させる事は難しいです。<br/>
    読むこととアウトプットの間を限りなく無くしていくことが重要であると私は考えます。<br/>
    その一つのきっかけとしてみんなで気軽にアウトプットしやすくなるサイトを考えました。
  </p>
</section>

<section class="scene" id="scene">
  <div class="container">
    <h2 class="heading">
      SCENES
    </h2>
    <div class="row mb-5">
      <div class="col-md-6 col-sm-12 mb-5 no-padding">
        <%= image_tag('tumi.jpg', class: 'image-fluid', :size => "200x200")%>
      </div>
      <div class="col-md-5 col-sm-12 no-padding">
        <span class="text-white">
          <%= icon('fas', 'book-reader', class: "fa-2x") %>
        </span>
        <h3 class="h4 my-4 scenes-title">
          読みたい本がたまってしまう
        </h3>
        <p class="scenes-content">
          インプットする積み本だけこのサイトへ登録しましょう。<br />
          <%= link_to books_path, {class: 'books_link' } do %>
            本の一覧
            <span>
              <%= image_tag('intro_book.png') %>
            </span>
          <% end %>
          ページより
          <%= link_to '#scene', { class: 'btn btn-primary btn-intro' } do %>
            <%= icon('fas', 'book', class: 'pr-1') %>
            <%= t('views.message.add_new_book') %>
          <% end %>
          をクリック！<br/>
          本が登録できたら
          <%= link_to '#scene', { class: 'btn btn-primary btn-intro' } do %>
            <%= icon('fas', 'pen', class: 'pr-1') %>
            <%= t('views.message.new_article') %>
          <% end %>
          をクリックし、<br/>
          どんどん記事を投稿していって下さい。<br/>
          <br/>
        </p>
      </div>
    </div>
    <div class="row mb-5">
      <div class="col-md-6 col-sm-12 no-padding">
        <span class="text-white">
          <%= icon('fas', 'laptop-code', class: 'fa-2x') %>
        </span>
        <h3 class="h4 my-4 scenes-title">
          一人では捗らない。
        </h3>
        <p class="scenes-content">
          同じ本を勉強している同士でアウトプットをシェアします。<br />
          人によってアウトプットの仕方は様々です。<br />
          様々な視点のアウトプットを共有できたら学習も深まるでしょう。<br />
          また本のグループにあなたのおすすめの本を登録していって下さい。<br/>
          他の人のおすすめしている本も見つけられるので、<br />
          学習のロードマップとして参考にしましょう。<br />
          <%= link_to '#scene', { class: 'btn btn-primary btn-intro' } do %>
            <%= icon('fas', 'book', class: 'pr-1') %>
            <%= t('views.button.regist_book') %>
          <% end %>
          をクリックする事で本の一覧に追加されます。
        </p>
      </div>
      <div class="col-md-5 col-sm-12 no-padding">
        <%= image_tag('background_book.jpg', class: "image-fluid", :size => "200x200")%>
      </div>
    </div>
    <p>
      scene descripton
    </p>
  </div>
</section>